apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: backend-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "backend-dev"
      images:
        - alias: backend
          imageName: ghcr.io/qandeland/gitops-platform/backend
          commonUpdateSettings:
            updateStrategy: newest-build
            forceUpdate: true
            pullSecret: "secret:argocd/ghcr-secret"
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
