replicaCount: 1
image:
  repository: ghcr.io/qandeland/gitops-platform/frontend
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  host: frontend.local
